


from enum import Enum


class ErrorCode(str, Enum):
	# General
	INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
	CONFLICT_ERROR = "CONFLICT_ERROR"
	NOT_FOUND = "NOT_FOUND"
	UNPROCESSABLE_CONTENT = "UNPROCESSABLE_CONTENT"
	UNAUTHORIZED = "UNAUTHORIZED"
	FORBIDDEN = "FORBIDDEN"
	LOCKED = "LOCKED"
	BAD_REQUEST = "BAD_REQUEST"

